### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by expenses** [AKGWSB/FFTConvolutionBloom#1]
你好, thank you very much for putting this implementation of FFT/convolution bloom online! The documentation on zhihu is also very useful (even when automatically translated to english: https://zhuanlan-zhihu-com.translate.goog/p/611582936?_x_tr_sl=mi&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp).

I would also like to implement this effect in my engine, using your code as a starting point. Would it be acceptable for you to license the code under MIT or even GPL so that others may use it?

Thank you!

**Comment by AKGWSB** [comment]
Thanks for your appreciate, i am glad to see my code can help. I have already add code under MIT license, wishing you a pleasant coding experience!!

**Comment by expenses** [comment]
Wonderful! I will chose this issue now.
